#
# spec file for package SFEmediawiki
#
# includes module(s): mediawiki
#
%include Solaris.inc

Name:                    SFEmediawiki
Summary:                 mediawiki - a free software wiki package originally written for Wikipedia
Version:                 1.9.3
Source:                  %{sf_download}/wikipedia/mediawiki-%{version}.tar.gz
SUNW_BaseDir:            /
BuildRoot:               %{_tmppath}/%{name}-%{version}-build
%include default-depend.inc
Requires: SUNWapch2u
Requires: SUNWmysqlu
Requires: SFEphp


%prep
%setup -q -n mediawiki-%{version}

%install
# Move the build directory to the install dir. Nothing to build in the package.
mkdir -p $RPM_BUILD_ROOT/var/apache2/htdocs
cd ..
mv mediawiki-%{version} $RPM_BUILD_ROOT/var/apache2/htdocs/wiki

# Expand tarball in BUILD area to create source package
%setup -q -n mediawiki-%{version}

# Remove script generated by pkgbuild to run this %install section.
rm $RPM_BUILD_ROOT/var/apache2/htdocs/wiki/.pkgbuild.install.sh

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr (-, root, bin)
%dir %attr (0755, root, sys) /var
# TODO: Consider making the /var/apache2/htdocs/wiki/config dir world writable.
/var/*

%changelog
* Sat Apr 21 2007 - Thomas Wagner
- bump to 1.9.3
- new download-url
* Fri Jan 19 2007 - daymobrew@users.sourceforge.net
- Add SFEphp dependency.
* Wed Jan 17 2007 - daymobrew@users.sourceforge.net
- Move files from root pkg to base pkg and just change basedir.
* Wed Jan 17 2007 - daymobrew@users.sourceforge.net
- Add TODO note about 'config' dir perms. Delete pkgbuild script before
  packaging.

* Wed Jan 17 2007 - daymobrew@users.sourceforge.net
- Initial spec

