#!/bin/sh

#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

cmd=""
DEVLIST="'"
echo "" > /tmp/__aliases__
for arg in "$@"
do
	echo $arg | egrep "pci|," > /dev/null
	if [ $? -eq 0 ]
	then
		for i in $arg
		do
			DEVLIST="${DEVLIST}$i "
			echo $i >> /tmp/__aliases__
		done
		DEVLIST="${DEVLIST}' "
		cmd="${cmd} \"\${DEVLIST}\" "
	else
		echo $arg | fgrep root > /dev/null
		if [ $? -eq 0 ]
		then
			cmd="${cmd}\"'$arg'\" "
		else
			cmd="${cmd}$arg "
		fi
	fi
done

echo "DLIST=${DEVLIST}"
echo "test_get_dev_list \$DLIST"
echo "check_add_drv "$cmd""
